### ISSUE TITLE
Feature request: Append to today's daily note

### ISSUE THREAD

**Issue by ankushg** [marcjulianschwarz/obsidian-raycast#12]

**Comment by marcjulianschwarz** [comment]
Hey @Gitznik,

I was quite busy because of exams for university but I do have time now which I will use to close some issues.
Of course you can contribute, you might want to read the discussion at #11.

**Comment by marcjulianschwarz** [comment]
I think the idea for custom commands (#11) might be a suitable way to implement this.
Do you know whether the daily note plug-in has a URI scheme for appending to a daily note?

**Comment by Gitznik** [comment]
I have no idea but I'll spend some time researching this 👍

**Comment by marcjulianschwarz** [comment]
Thank you.

I am currently restructuring the code for this extension to make it a bit easier to read and work on.

**Comment by marcjulianschwarz** [comment]
I just closed issue #11 which requested opening daily notes. This was rather easy to implement by using the Advanced URI plugin for Obsidian. 
With the new `Daily Note` command you will be able to open the daily note in Obsidian or create and open a new daily note if it doesn't exist yet.

Maybe this covers this issue too? I think appending text to a daily note is rather easy when you can quickly open that note from Raycast.

**Comment by Gitznik** [comment]
Rapid work there! I'll check it out as soon as it's in the raycast repo and see if it resolves my workflow issue 👍

**Comment by marcjulianschwarz** [comment]
This feature has now been released.

https://www.raycast.com/marcjulian/obsidian

**Comment by timkelty** [comment]
@marcjulianschwarz far as I can tell, the "daily note" command just opens the daily note in Obsidian.
I'm looking for a prompt to capture text and _append_ to the daily note.
