### ISSUE TITLE
Vault Not Found using Open in Obsidian

### ISSUE THREAD

**Issue by orand** [marcjulianschwarz/obsidian-raycast#13]
Search Note works great when I use Quick Look as my primary action.  When I change that to Open in Obsidian, search still works, but opening the selected item takes me to Obsidian and displays an error message:

Vault not found
Unable to find a vault for the URL obsidian://open?path=%2Fusers%2Fmyusername%2FObsidian%2FVault%20Name%2Ftest%20file.md

**Comment by marcjulianschwarz** [comment]
Could you please share the path to your vault (the one you entered in Raycast)?

**Comment by orand** [comment]
`/users/myusername/Obsidian/Vault Name`

**Comment by marcjulianschwarz** [comment]
If you are on a Mac your path should start with `/Users` and not `/users`. Looks like the Obsidian URI won't work when you don't use the correct upper- and lowercase letters.

**Comment by orand** [comment]
Oh man, you're 100% right! Your plugin handles it correctly, and Obsidian doesn't!  I've been the guy to catch obscure casing issues for others more times than I can count, so very much appreciate you noticing that for me.
