### ISSUE TITLE
Daily Note command not working with a vault

### ISSUE THREAD

**Issue by jiserra** [marcjulianschwarz/obsidian-raycast#15]
I have only two vaults. Both vaults are configured with the Daily Notes plugin and I also have the Advanced URI plugin installed. For some reason, the extension is telling me that the Daily Note plugin is not installed in one of my vaults when I invoke the Daily Note command.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/768734/163213538-b853d79f-b183-4a89-a149-8374985892d9.png">

Any clues?

**Comment by marcjulianschwarz** [comment]
Can you make sure that the Advanced URI plugin is enabled?

Is the path to the `Work Record` vault correct? Try out the other commands with that vault.

Could you send me a copy of the content of `Work Record/.obsidian/community-plugins.json`?

The message might be a bit misleading, it is actually checking whether the Advanced URI plugin is installed or not.

**Comment by jiserra** [comment]
Thanks for your questions! It seems that the problem was that I was not aware that I have to install the Advanced URI plugin on each vault, I thought that the plugin was for the whole Obsidian installation.

I realize that when there was no `community-plugins.json` on the `.obsidian` folder on that vault.
