### ISSUE TITLE
Feature request: Add Obsidian tags as searchable keywords

### ISSUE THREAD

**Issue by RobertBolender** [marcjulianschwarz/obsidian-raycast#16]
The Raycast List.Item allows for a `string[]` of keywords that are indexed for searching, which would allow for tags to be fuzzily-searchable in the Search Note command in addition to note titles.

https://developers.raycast.com/api-reference/user-interface/list#props-5

I'm currently aware of two different approaches for Obsidian tagging: in YAML front matter or else in the body with `#` hashtags, which might complicate this feature.

https://help.obsidian.md/How+to/Working+with+tags

**Comment by marcjulianschwarz** [comment]
Hi @RobertBolender,

I am aware of the keywords property and I already did some testing with it. Tried to implement a content search. It did work but the performance wasn't great.

Maybe it will be better when only tags will be used for searching. I will give it a go.

Thank you for the suggestion.

**Comment by marcjulianschwarz** [comment]
Didnt forget this issue, but I need help as I am having problems with the JS heap being out of memory when reading the content for every note (which would be necessary for everything listed here), especially for search related tasks.

See issue https://github.com/marcjulianschwarz/obsidian-raycast/issues/19 for more info and further discussion.

**Comment by marketmann** [comment]
This would be sweet!

**Comment by marcjulianschwarz** [comment]
This has been implemented with the new version 1.6.0 which has just been released on the store.
