### ISSUE TITLE
Directory containing multiple vaults

### ISSUE THREAD

**Issue by fatlazycat** [marcjulianschwarz/obsidian-raycast#21]
Is it possible to point the prefs to a directory that contains multiple vaults ? 

Assume that every directory underneath the one specified is an individual vault ?

Thanks

**Comment by marcjulianschwarz** [comment]
Hi @fatlazycat,
thank you for the suggestion.
Vaults that were opened in Obsidian will be detected automatically with the upcoming version. Thus you won’t need to specify vaults anymore.

 Does this solve your problem?

**Comment by fatlazycat** [comment]
Ah sounds great. Yeah that would do thanks

**Comment by marcjulianschwarz** [comment]
Will let you know when then update has been released (probably until end of next week).

**Comment by marcjulianschwarz** [comment]
Hi @fatlazycat,

the update has now been released. Vaults will now be detected automatically.
