### ISSUE TITLE
Fallback Action

### ISSUE THREAD

**Issue by cyrulnik** [marcjulianschwarz/obsidian-raycast#23]
Thanks for this plugin. Just started using it -- and apologies if I'm missing something obvious. But is there a way to configure Obsidian note search to work as a fallback command in Raycast so that it would be available (along with Google search, etc.) to use on any text that is typed directly into the search bar?

**Comment by marcjulianschwarz** [comment]
I don't know whether I understand your issue correctly but here are a few clarifications and one suggestion:

"Obsidian for Raycast" is an extension for Raycast that adds various commands like "Search Note", "Create Note", etc.
You can use these commands from the Raycast search, just like you can use the Google search right from the Raycast search.

There is no way to override the default Raycast search.

You can however assign a keyboard shortcut to the Obsidian search:
- navigate to the "Note Search" command
- press `cmd + k`
- scroll down the menu to "Configure Command" or use `cmd + shift + ,`
- click on the hotkey section and assign your prefered keyboard shortcut

Now you can open Obsidian search from anywhere just by pressing the keyboard shortcut.

**Comment by cyrulnik** [comment]
Sorry - should have been more clear. Raycast has two ways of doing a Google search (or a file search, etc.) One is that you bring up the Raycast search box, go to Google search, press "enter" and then start searching. The other is that you bring up the Raycast input box, type your search terms without first triggering a google search, and the select google search after the fact. Raycast calls these fallback commands -- as discussed in the linked document.

https://manual.raycast.com/fallback-commands

If you trigger the Raycast input window and start typing a google search

**Comment by marcjulianschwarz** [comment]
Thank you for the clarifications.

I don't think that it is currently possible for third-party extensions to configure fallback commands. I haven't found anything in the [API documentation](https://developers.raycast.com) and there are no [third-party extensions](https://github.com/raycast/extensions/tree/main/extensions) supporting fallback. At least I couldn't find any.

However I really like the idea of these fallback commands. Maybe you can open a feature request at raycast or contact them about it.

**Comment by marcjulianschwarz** [comment]
Hey @cyrulnik,

this might not be exactly what you want but Raycast just announced [Arguments for Commands](https://developers.raycast.com/information/arguments). I will add this to the extension.
However as far as I can tell these still dont work as fallback commands. I think this might come soon.

**Comment by marcjulianschwarz** [comment]
Looks like this:

https://user-images.githubusercontent.com/67844154/180615837-4ae97c57-9b8b-4dd3-8861-6dd707193a85.mov

**Comment by marcjulianschwarz** [comment]
You can add your own fallback commands with [Quick Links](https://manual.raycast.com/quicklinks).

This Quick Link will open Obsidian, open the vault "Second Brain" and search for the query (text you entered in the Raycast search) in Obsidian:

```
obsidian://search?vault=Second%20Brain&query={Query}
````

This Quick Link will open Obsidian, open the vault "Second Brain" and open the note:

```
obsidian://open?vault=Second%20Brain&file={Note}
```

Make sure to select Obsidian as application for `Open With`:

<img width="563" alt="Bildschirmfoto 2022-08-23 um 21 24 13" src="https://user-images.githubusercontent.com/67844154/186248504-7a9e7ee6-30c1-48fd-ade8-630cf7adffff.png">

Also make sure to go to `Configure Fallback Commands` and add the Quick Links there.

If you want to go even further, you can enable [Quick Search (see further down)](https://manual.raycast.com/quicklinks) which allows you to trigger the Quick Links with your selected text.
