### ISSUE TITLE
Create New Note Open Note On Creation (File not found even though File is created successfully on Obsidian)

### ISSUE THREAD

**Issue by briansport13** [marcjulianschwarz/obsidian-raycast#26]
Hi, I have a problem where every time I create a new note with the create note extension,n it would always say that the file that I just created doesn't exist even though when I made the note, the note was created & Obisidan was launched. But for some reason, it would never open.

**Comment by marcjulianschwarz** [comment]
This was an issue with Obsidian not recognizing the file fast enough. It would only occur when Obsidian was already open.

Should be fixed with the newest version by adding a short delay before the note is opened in Obsidian.
