### ISSUE TITLE
[FR] Command (or action) to quickly append text to the current daily note

### ISSUE THREAD

**Issue by marcjulianschwarz** [marcjulianschwarz/obsidian-raycast#31]
## To Do
- should this be yet another command that can only be used together with the Advanced URI plugin or rather restructure the existing daily note command to add actions?
    - reduce number of commands that not every user can use 
    - adds possibility for more daily note actions
    - Con: adds one extra step to interact with daily notes 

---
Feature Request from @carlosflorencio on Raycast Slack.

**Comment by hellostanley** [comment]
+1 similar functionality to Alfred app, shown in this workflow: 

https://youtu.be/ZD-P0lTkQMw
