### ISSUE TITLE
[FR] support search markdown headings in the notes

### ISSUE THREAD

**Issue by simpzan** [marcjulianschwarz/obsidian-raycast#37]
It would be great if I can search headings in notes by prefixing the keyword with `#` char. for example:
1. keyword `#introduction` to search `introduction` in headings of all notes.
2. keyword `markdown#introduction` to search `introduction` heading in note with `markdown` in the title.

when use opening the searched note, heading parameter in https://vinzent03.github.io/obsidian-advanced-uri/actions/navigation can be used to open the note and navigate to the target heading.

**Comment by marcjulianschwarz** [comment]
Hi @simpzan, thank you for your suggestion. This seems to be quite a use case specific issue as you can already search for headings with `# heading`, `## smaller heading`, ...

I might look into this later. Added it to the "Waiting" list of the roadmap.

**Comment by marcjulianschwarz** [comment]
Closing this issue as searching for headings is already possible. 

Opening #47 to add a similar feature that might be helpful in this context.
