### ISSUE TITLE
[FR] Add create option to search

### ISSUE THREAD

**Issue by timkelty** [marcjulianschwarz/obsidian-raycast#38]
I would love to use this extension with the [Notational Velocity](https://notational.net/)-style combined search/create action.

That is, results filter as you search, but at any time if you're not seeing the results you want, you can create a note with the contents of your search.

In terms of how this would work in Raycast, I would think just adding a `cmd-K` action for "Create new note…" in the search context, and then maybe when you search and have no results, you get a "create note" result so you can just hit return.

**Comment by marcjulianschwarz** [comment]
Thank you for the feature request. Sounds like a really useful feature, added it to the backlog.

**Comment by marcjulianschwarz** [comment]
Has been added to the new version. The extension should update automatically. You can get it here: https://www.raycast.com/marcjulian/obsidian
