### ISSUE TITLE
feature: Configure primary action

### ISSUE THREAD

**Issue by HEmile** [marcjulianschwarz/obsidian-raycast#4]
It would be great if I could use enter instead of cmd + enter to open the note in Obsidian, as I'd never want to open it in Raycast. The Snippets extension seems to do this with 'primary action'

**Comment by marcjulianschwarz** [comment]
Which Snippets extension do you mean?

**Comment by HEmile** [comment]
This one, I think it's included by default. At the bottom you can configure a primary action. ![image](https://user-images.githubusercontent.com/1289165/146331511-8b8308d4-4a0a-4975-9ddc-09c05cbca91a.png)

**Comment by marcjulianschwarz** [comment]
Thank you, will have a look at this.

**Comment by marcjulianschwarz** [comment]
Primary actions have been added with the new commits. However this version hasn't been reviewed yet and thus isn't available in the store right now.

**Comment by marcjulianschwarz** [comment]
The new features are now available in the store:
https://www.raycast.com/marcjulian/obsidian
