### ISSUE TITLE
Can't seem to set the Path in preferences

### ISSUE THREAD

**Issue by huyz** [marcjulianschwarz/obsidian-raycast#40]
I have no idea what I'm doing wrong but I can't get search to work.

But every time I try to search, I get "The path set in preferences doesn't exist Please set a valid path in preferences".

I've checked 10 different times and I've tried the root of a Vault, the parent directory of the Vaults, dereferenced all the symbolic links.  Nothing works.

**Comment by marcjulianschwarz** [comment]
Do you have full disk access enabled for Raycast (in settings under security)?
Otherwise the extension will probably not work.

**Comment by marcjulianschwarz** [comment]
No problem. Will add this to the error notification to make it a bit more clear.
