### ISSUE TITLE
Feature: Append to search note

### ISSUE THREAD

**Issue by chnejohnson** [marcjulianschwarz/obsidian-raycast#42]
## Requirement
- User can append new content in an existing note.

## Scenario

I know there is a todo list in my vault like this
```md
# Todos
- [ ] take out the trash

```

When I'm working on something and an idea pops into my mind. I have to wash the dish for my Mom. So I want to add a checkbox in the above note like `- [ ] wash the dish` and no need to interrupt current work (switch to Obsidian...etc)

**Comment by marcjulianschwarz** [comment]
You can use the keyboard shortcut `cmd + k` to show actions in the search note command. There should be both an append action and an append selected text action.
For more details, visit this [README](https://github.com/marcjulianschwarz/obsidian-raycast#overview).

<img width="785" alt="Bildschirm­foto 2023-01-14 um 23 51 55" src="https://user-images.githubusercontent.com/67844154/212500582-d7409b90-d557-4aff-9ffc-2ae9a9af4406.png">

**Comment by chnejohnson** [comment]
Ah, thank you for pointing that out!
