### ISSUE TITLE
[Feature] Don't jump to note after append

### ISSUE THREAD

**Issue by adhusson** [marcjulianschwarz/obsidian-raycast#43]
It would be useful to have a toggle or an alternate shortcut for not going to a note after appending. I'm interested in using "Append to Daily Note" to throw random thoughts in my daily note without interrupting the flow, and not moving focus would help a lot with that.

**Comment by marcjulianschwarz** [comment]
Hey @adhusson, thank your for the suggestion.

The "Append to Daily Note" command relies on the "Advanced URI Plugin" for Obsidian, thus it is not possible to append to a daily note without opening Obsidian itself.
However there is a way to make it only open Obsidian (but not the file itself). Would that solve the problem?

**Comment by marcjulianschwarz** [comment]
This shows how it would look like, if the daily note is not open at the moment, you can just go on with your work and append notes to the daily note without opening it.

https://user-images.githubusercontent.com/67844154/216767371-3a41cf58-2479-4a73-8066-b582ed1d2a7c.mov

**Comment by marcjulianschwarz** [comment]
Has been added to the new version. The extension should update automatically. You can get it here: https://www.raycast.com/marcjulian/obsidian

**Comment by adhusson** [comment]
Thank you this will already be an improvement!
