### ISSUE TITLE
FR: Any considerations for porting to Flow-Launcher on Windows

### ISSUE THREAD

**Issue by j-maffe** [marcjulianschwarz/obsidian-raycast#46]
Hello!
This extension looks absolutely incredible! Have you considered porting it to the Flow-launcher app on Windows? There's already an Obsidian extension for it, but it doesn't provide nearly as much as what you offer here.

**Comment by marcjulianschwarz** [comment]
Hi @j-maffe,

It is not planned to port this extension to Windows launcher apps for the near future.
