### ISSUE TITLE
Is it possible to add support for preview of formula (Mathjax)?

### ISSUE THREAD

**Issue by jianghao-zhang** [marcjulianschwarz/obsidian-raycast#48]
Thanks again for developing such good extension.
I want to ask is it possible to add support for preview of formula ($ $, $$ $$) in the future?

**Comment by marcjulianschwarz** [comment]
Thanks so much! I will ping the Raycast API team to suggest LaTeX rendering for math equations. I think it would be better to implement this directly in Raycast, rather than in this extension.
