### ISSUE TITLE
Command palette

### ISSUE THREAD

**Issue by imeed166** [marcjulianschwarz/obsidian-raycast#5]
Can you show the command palette with all its commands within raycast ?

**Comment by marcjulianschwarz** [comment]
Yes, press `cmd + k` and you will see all commands.

**Comment by imeed166** [comment]
No, I mean replace the obsidian command palette entirely in obsidian. I'll open it via raycast. For now, there is only search,  I was thinking, make all the commands accessible in raycast. I don't know if it's possible.

**Comment by marcjulianschwarz** [comment]
Oh now I see, no it is not possible to add all commands. This extension is not made to replace the default command palette in obsidian therefore not all commands from obsidian would make sense in this extension.

Right now there are these commands:
- "search" (default command)
- view and open note
- copy and paste note
- append text to note

which you can access with keyboard shortcuts.

You can request new commands (that make sense in raycast) and I will see if I can implement them.

**Comment by imeed166** [comment]
I see, thank you for the explanation.
