### ISSUE TITLE
Add "Append task"

### ISSUE THREAD

**Issue by mikejongbloet** [marcjulianschwarz/obsidian-raycast#51]
Feature idea:

There are two 'quick capture' problems I'm trying to solve - quick capture a note and quick capture a task.

It would be amazing if it were possible to either specify two templates, or if I could set up a second quick capture command somehow.

Do you have any thoughts or guidance?

Thank you

**Comment by mikejongbloet** [comment]
Thinking a bit more about this, what I'm actually looking to do is "Append to note" where I can specify a string to be appended and a note.

**Comment by mikejongbloet** [comment]
Hey @marcjulianschwarz -

I've developed this locally on a fork of your repository. The command does the following:

- Takes a path setting to select a note
- Takes a task string and a date as arguments
- Takes a heading argument
- Appends the task to the selected note

I'm not an engineer, but I kind of know my way around a little.

What I'm not sure about is how to send it to you for consideration to merge in. Raycast suggests I run `npx ray publish` but I was a bit concerned that would publish the addition without your approval.

I then tried pushing a branch to your repository to open up a Pull Request but got a permission denied message.

Would you be able to point me in the right direction?

p.s. one thing that confused me a little was that the fork I pulled from your git repo didn't have `arguments` in the JSON manifest. In adding the new command I've also added in arguments for the other tasks in that manifest.

**Comment by mikejongbloet** [comment]
Uploading a video here of it in action: https://www.youtube.com/watch?v=MrqpTLoICPc

**Comment by marcjulianschwarz** [comment]
Hi @mikejongbloet,

this looks nice. Could you please push the local branch to your own github profile? You can then open a pull request in the forked repo.

**Comment by mikejongbloet** [comment]
Hey @marcjulianschwarz…I think I've done that…I've not contributed to a repo before but I followed Githubs forking and PR documentation and I think it's worked.

Let me know.

Thanks
Mike

**Comment by marcjulianschwarz** [comment]
Accepted the pull request.
