### ISSUE TITLE
content search 

### ISSUE THREAD

**Issue by bagameow** [marcjulianschwarz/obsidian-raycast#6]
Perhaps we can have a feature to search note content?
It could show a list of files matched with the query.

Actually, there are some integrations implemented with Alfred(another similar application like Raycast) here.
https://github.com/chrisgrieser/shimmering-obsidian#feature-overview
If you need ideas, this will help.

**Comment by marcjulianschwarz** [comment]
Thank you for the feature request.

If I understand it correctly, the extension should be able to process searches with these four methods:
- search by content
- search by tag
- search by filename (already implemented)
- search by YAML frontmatter entry (#1)

Do you think it would make sense to put all these methods into the one existing command or should I split them up into four separate commands?
I think I will have to test whether this will lead to a worse performance as more keywords have to be queried to display the list of notes in a search.

Another solution would be to create a "syntax" like `#tagname` to search for the tag `tagname`.

Nonetheless the extension would need to read every files content which might have a big impact on performance.

Will let you know when I got something working.

**Comment by marcjulianschwarz** [comment]
It seems like searching notes by content won't work with the current Raycast API. The memory limit for the application is quickly reached when using their keywords argument for list items.
Sadly I can not create my own search within Raycast.

But I like the idea of having different search methods. I will now work on searching by tags and YAML entries.

**Comment by marcjulianschwarz** [comment]
Will close this now. I did however open a new issue #9 , which addresses the tag search.

**Comment by marcjulianschwarz** [comment]
Hi @bagameow,

the newest version of Obsidian for Raycast now supports content and tag search. You can try it out by cloning this repository and running `npm install && npm run dev`.

**Comment by rbreaves** [comment]
Not sure what this means.. I have only 2 markdown files in my Obsidian app and this plugin seems incapable of searching content in the files still. Guess I will be using Bear.

**Comment by rbreaves** [comment]
Oh I see now.. "Full content search" is not check marked by default. I would definitely make that a default if possible o.o. I can't think of a scenario where people would not be wanting to search the content of their notes unless the search was super slow for some reason.
