### ISSUE TITLE
[FR]: Create new note from input

### ISSUE THREAD

**Issue by arminta7** [marcjulianschwarz/obsidian-raycast#8]
Create new note by entering a title then whatever text should be in the body. Without opening Obsidian.

**Comment by marcjulianschwarz** [comment]
Got it working, will let you know when the new version is available in the store.

<img width="838" alt="Bildschirmfoto 2022-01-12 um 23 45 29" src="https://user-images.githubusercontent.com/67844154/149235045-5eae9fa3-660b-40d9-be94-45000dab4fe6.png">

**Comment by arminta7** [comment]
Holy moly you're amazing!! Thank you!

**Comment by marcjulianschwarz** [comment]
The update is still under review but I think it can be published soon.

Just wanted to let you know that I added a tag picker to the "Create Note" command. The selected tags will be added to the notes YAML frontmatter like this:

```
---
tags: ["tag1", "tag2"]
---
```

<img width="831" alt="Bildschirmfoto 2022-01-16 um 12 41 51" src="https://user-images.githubusercontent.com/67844154/149658745-75ccb7a7-d8cc-4c92-ab49-f8c72fba7c7f.png">

**Comment by marcjulianschwarz** [comment]
Hey @arminta7,
the update (with your requested feature) is now available in the store.
Here is the link if you want to install it:
https://www.raycast.com/marcjulian/obsidian
